### ISSUE TITLE
Eng Management 

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/README#15]
- [ ] 1:1s and skip 1:1s 
- [x] what EMs are typically responsible for 
- [x] what director of engineering, management is responsible for
- [ ] EM tools & resources:
  - [ ] How to efficiently schedule meetings

**Comment by KatieLo** [comment]
Core Accountabilities of Engineering Managers 

1. Engagement & retention of Engineers 
  Engineers are meeting their role expectations, have a healthy, supportive work environment, and are getting the encouragement, recognition and feedback needed to keep succeeding and to grow professionally.
  1:1s, career roadmaps, promotion motivations, team retros and learning syncs all go here


2. Delivery of the product
  The team is productive, delivering software of an agreed quality standard, in a predictable and reasonable time frame.
  (While “predictable and reasonable” is fuzzy, Multiple Composers is a nice clear example of way off track when it comes to predictable & reasonable time frame and acceptable quality. We didn’t have an EM who’s been consistently involved there). 
  Team cycle planning to get rough estimates, surfacing challenges that could hamper a team's ability to deliver, and cross-team dependency coordination and project management fall here.

All Managers: stewardship and shepherding of culture, actively exemplifying and promoting our values and culture.

**Comment by KatieLo** [comment]
Buffer Director of Engineering, Management:
1. People & Culture: I oversee all aspects of engineering management, recruitment, retention and culture, so that we have a highly effective team that also demonstrates care for each individual’s personal development, career progression and mental wellbeing.
  Manager 1:1s, skip-level 1:1s, career frameworks, overseeing the hiring process, and engineering-wide culture initiatives fall here.
  
1. Delivery & Operations: I am accountable to overall engineering delivering on our product strategy and vision in a way that is timely, of the chosen quality level, and long-run sustainable for all engineering’s stakeholders. I’m accountable to teams across engineering having the right types and amount of structure to work smoothly and transparently. Our processes serve our people, our products and our customers.
  Overall processes like how we prioritize large/complex cross-team projects, plan cycles, the tools we use, documenting decisions, and team growth planning fall here.
